const data = [
    {
        id: '1',
        name: 'John Brown',
        date: '27, Feb 2023',
        details: 'Web development',
        desc: 'Six web page designs and three times revision',
        amount: '#120,000',
        status: ['Paid'],
        paymentType : 'Bank Transfer',
        department : 'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '#120,000',
        acctManager: 'Jhon Donate',
        receipient: 'John Wayne PLC,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Crater365 Application',
        ceo: 'John Doe'
      },
      {
        id: '2',
        name: 'Jim Green',
        date: '13, Feb 2023',
        details: 'Maintenance',
        desc: 'Convert pixel-perfect frontend and make it dynamic',
        amount: '#372,000',
        status: ['Failed'],
        paymentType : 'Credit Card',
        department : 'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '#372,000',
        acctManager: 'Jhon Donate',
        receipient: 'Microsoft,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Web Development',
        ceo: 'John Doe'
      },
      {
        id: '3',
        name: 'Joe Black',
        date: '7, Feb 2023',
        details: 'Train Booking',
        desc: 'Android & Ios Application Development',
        amount: '#500,000',
        status: ['Pending'],
        paymentType : 'Cash',
        department :  'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '#500,000',
        acctManager: 'Jhon Donate',
        receipient: 'Laralink Ltd,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'App Development',
        ceo: 'John Doe'
      },
      {
        id: '4',
        name: 'Fatima Bello',
        date: '7, Feb 2023',
        details: 'Leave Allowance',
        desc: 'Cash',
        amount: '231,000',
        status: ['pending'],
        paymentType : 'Credit Card',
        department :   'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '231,000',
        acctManager: 'Jhon Donate',
        receipient: 'Laralink Ltd,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Web Development'
      },
      {
        id: '5',
        name: 'Stephanie Donald',
        date: '18, Jan 2023',
        details: 'Train Booking',
        desc: 'Cash',
        amount: '500,000',
        status: ['pending'],
        paymentType : 'Credit Card',
        department :   'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '372,000',
        acctManager: 'Jhon Donate',
        receipient: 'Laralink Ltd,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Web Development'
      },
      {
        id: '6',
        name: 'Ade Tunde',
        date: '7, Feb 2023',
        details: 'Train Booking',
        desc: 'Cash',
        amount: '500,000',
        status: ['pending'],
        paymentType : 'Credit Card',
        department :   'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '372,000',
        acctManager: 'Jhon Donate',
        receipient: 'Laralink Ltd,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Web Development'
      },
      {
        id: '7',
        name: 'Aisha Muhammad',
        date: '2, Mar 2023',
        details: 'Staff Training',
        desc: 'Credit Card',
        amount: '130,000',
        status: ['pending'],
        paymentType : 'Credit Card',
        department :   'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '130,000',
        acctManager: 'Jhon Donate',
        receipient: 'Laralink Ltd,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Web Development'
      },
      {
        id: '8',
        name: 'Daniel Kingsley',
        date: '7, Feb 2023',
        details: 'Logistics',
        desc: 'Cash',
        amount: '72,000',
        status: ['paid'],
        paymentType : 'Cash',
        department :   'IPI Solutions,3rd Floor, Veterinary Council Building, Plot,8 Zambezi Crescent, Maitama,Nigeria.',
        qty: '1',
        total: '72,000',
        acctManager: 'Jhon Donate',
        receipient: 'Laralink Ltd,86-90 Paul Street, Wuse 2,Nigeria.demo@gmail.com',
        item: 'Web Development'
      }
]

export default data;